### ISSUE TITLE
starting?

### ISSUE THREAD

**Issue by jayhill365** [ZiaUrR3hman/FacebookAutoLikeProfessional#2]
How do you actually start and run this script? I seem to have everything downloaded but when I try and start and enable the script in tampermonkey nothing seems to happen?

**Comment by jayhill365** [comment]
Wow this is self explanatory all I needed to do after downloading this script was open up facebook and sign in and after that the facebookautolikeproffesional widget showed up in the bottom left hand corner however after 20 comments I was asked to pay $... Still a good tool for automated liking thanks!

**Comment by ZiaUrR3hman** [comment]
Hi, I've added the unlimited Comments support in latest version... Check that out...
