### ISSUE TITLE
Activation Key?

### ISSUE THREAD

**Issue by thecube69** [ZiaUrR3hman/FacebookAutoLikeProfessional#4]
Hello,

I read several times your how to but I didn't understand where I can find the Activation key?

I have my Facebook page ID but how can I get the activation key?

Thank you very much for your help

**Comment by ZiaUrR3hman** [comment]
it is premium Feature, you need to purchase Activation Key to use this feature...

**Comment by thecube69** [comment]
Oh okey I understand.

How much is it and where can I buy it?

Thank you

**Comment by ZiaUrR3hman** [comment]
$50, inbox ziaurr3hman@hotmail.com

**Comment by thEpisode** [comment]
faaaaaaaaaaake!

**Comment by ZiaUrR3hman** [comment]
Not fake, its is working...

**Comment by Luonghenrygate** [comment]
Thanks you,but it still work now

**Comment by ZiaUrR3hman** [comment]
Yes, it works perfectly, i released latest version 12 days ago...

**Comment by Luonghenrygate** [comment]
Could you give me a discount?

**Comment by ZiaUrR3hman** [comment]
$20 key price...

**Comment by Luonghenrygate** [comment]
I know, brother. I will contact you later.
